# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.21.0
import dataclasses
import datetime
import enum


class Roletype(str, enum.Enum):
    USER = "user"
    ADMIN = "admin"


@dataclasses.dataclass()
class PontusApiKey:
    id: int
    username: str
    password: str
    role: Roletype
    enabled: bool
    created_at: datetime.datetime
    updated_at: datetime.datetime
