# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.21.0
import dataclasses
from typing import Any


@dataclasses.dataclass()
class Node:
    id: int
    content: str
    metadata: Any
    embedding: Any
