# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.21.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class VectorStore:
    id: int
    content: Optional[str]
    metadata: Optional[Any]
    embedding: Optional[Any]
